# Generated by Django 4.2.10 on 2024-02-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senseiapp', '0002_remove_teacher_areas_of_expertise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teacher_list',
            field=models.ManyToManyField(to='senseiapp.teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='student_list',
            field=models.ManyToManyField(to='senseiapp.student'),
        ),
    ]
