# Generated by Django 4.2.10 on 2024-02-27 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senseiapp', '0003_student_teacher_list_teacher_student_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher_list',
        ),
    ]
