# Generated by Django 4.2.10 on 2024-02-28 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senseiapp', '0007_alter_teacher_student_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.IntegerField()),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='senseiapp.teacher')),
                ('teacher', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='senseiapp.student')),
            ],
        ),
    ]
