# Generated by Django 4.2.10 on 2024-03-03 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senseiapp', '0008_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='latitude',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
    ]
