# Generated by Django 4.2.10 on 2024-03-03 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('senseiapp', '0009_rename_latitude_user_location_remove_user_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='senseiapp.student'),
        ),
        migrations.AlterField(
            model_name='review',
            name='teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='senseiapp.teacher'),
        ),
    ]
